### ISSUE TITLE
uncomplete code

### ISSUE THREAD

**Issue by a349101311** [youmi-zym/AcfNet#1]
First,thanks for your outstanding work and open source spirit.But the code currently provided seems to be incomplete.Would you please push the complete code on github?

**Comment by youmi-zym** [comment]
Appreciating your interest in our work, I'm working on it, please wait...

**Comment by youmi-zym** [comment]
Please refer to https://github.com/DeepMotionAIResearch/DenseMatchingBenchmark for training details. I'm sorry for the delay, and I'll update this repo for more functions in Jan.
