### ISSUE TITLE
Question about the calculation of confidence map

### ISSUE THREAD

**Issue by MASTERCHIEF343** [youmi-zym/AcfNet#2]
Hi, thanks to your paper and code, it's really impressive.I have a question about the calculation of confidence map.You use 3x3 window as neighborhood to calculate confidence map.Is there any reason to choose the size of window?I think 3x3 maybe too samll, it doesn't have enough receptive field for edge or occlusion.

**Comment by youmi-zym** [comment]
@MASTERCHIEF343 
Hi, 
As for the confidence estimation network, it's valuable to point out that the aggregated cost volume servers as input, which has collected considerable context information and is able to provide the matching confidence of each pixel. So, with the knowledge about the matching distribution of each pixel, we only use a 3x3 window to measure the confidence by considering its near neighbors. I think it does have enough receptive fields.
